version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - qgis-server-net
    depends_on:
      - qgis-server

  qgis-server:
    image: "camptocamp/qgis-server:latest"
    environment:
      # QGIS Server configuration
      QGIS_SERVER_LOG_LEVEL: "2"
      QGIS_SERVER_LOG_STDERR: "1"
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: "4"
      QGIS_SERVER_WMS_MAX_HEIGHT: "5000"
      QGIS_SERVER_WMS_MAX_WIDTH: "5000"
      
      # Landing page configuration
      QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES: "/project||/project/bee_farming_project||/project/tokyo"
      QGIS_SERVER_LANDING_PAGE_PROJECTS_THUMBNAIL_RESPONSIVE: "true"
      QGIS_SERVER_LANDING_PAGE_PROJECTS_THUMBNAIL_WIDTH: "400"
      QGIS_SERVER_LANDING_PAGE_PROJECTS_THUMBNAIL_HEIGHT: "300"
      QGIS_SERVER_PLUGINPATH: "/var/www/plugins"
      QGIS_PLUGINPATH: "/var/www/plugins"
      QGIS_SERVER_PLUGIN_ProjectInfo: "1"
        
      # Apache/FCGI tuning
      FCGID_MAX_REQUESTS_PER_PROCESS: "1000"
      FCGID_MIN_PROCESSES: "2"
      FCGID_MAX_PROCESSES: "10"
      FCGID_BUSY_TIMEOUT: "300"
      FCGID_IDLE_TIMEOUT: "300"
      FCGID_IO_TIMEOUT: "60"
      
      # Make sure QGIS has a writable directory for auth database
      QGIS_CUSTOM_CONFIG_PATH: "/tmp/qgis_cache"
      QGIS_AUTH_DB_DIR_PATH: "/tmp/qgis_cache"
    networks:
      - qgis-server-net
    ports:
      - "8080:8080"  # Note: The Camptocamp image uses port 8080, not 80
    volumes:
      # Mount projects directory to /project (where the image expects it)
      - ./projects:/project:ro
      # Mount custom plugins if needed
      - ./plugins:/var/www/plugins:ro
      # Create a cache volume for QGIS
      - qgis_cache:/tmp/qgis_cache
    restart: unless-stopped

networks:
  qgis-server-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  qgis_cache: