version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - qgis-server-net
    depends_on:
      - qgis-server

  qgis-server:
    image: "camptocamp/qgis-server:latest"
    environment:
      # QGIS Server configuration
      QGIS_SERVER_LOG_LEVEL: "2"
      QGIS_SERVER_LOG_STDERR: "1"
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: "4"
      QGIS_SERVER_WMS_MAX_HEIGHT: "5000"
      QGIS_SERVER_WMS_MAX_WIDTH: "5000"
      QGIS_PROJECT_FILE: ""  # Set to blank to allow using map parameter in GET requests
      
      # Landing page configuration
      QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES: "/var/www/projects||/var/www/projects/bee_farming_project"
      
      # Apache/FCGI tuning
      FCGID_MAX_REQUESTS_PER_PROCESS: "1000"
      FCGID_MIN_PROCESSES: "2"
      FCGID_MAX_PROCESSES: "10"
      FCGID_BUSY_TIMEOUT: "300"
      FCGID_IDLE_TIMEOUT: "300"
      FCGID_IO_TIMEOUT: "60"
      
      # Custom configurations for permissions
      QGIS_CUSTOM_CONFIG_PATH: "/tmp/qgis"
      
      # For debugging
      QGIS_DEBUG: "1"
      
    networks:
      - qgis-server-net
    ports:
      - "8080:80"  # The Camptocamp image exposes Apache on port 80
    volumes:
      # Mount projects directory
      - ./projects:/var/www/projects
      # Mount custom plugins if needed
      - ./plugins:/var/www/plugins
      # Mount temporary directory with proper permissions
      - ./tmp:/tmp
    restart: unless-stopped
    # Removed user: "www-data" directive

networks:
  qgis-server-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: