version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - qgis-server-net
    depends_on:
      - qgis-server

  qgis-server:
    image: "sourcepole/qwc-qgis-server:3.34"
    environment:
      # QGIS Server configuration
      QGIS_SERVER_LOG_LEVEL: "0"  # Most verbose logging
      QGIS_SERVER_LOG_STDERR: "1"
      QGIS_PLUGINPATH: "/usr/share/qgis/python/plugins"
      QGIS_SERVER_PLUGIN_ProjectInfo: "1"
      # Additional settings
      FCGID_EXTRA_ENV: 'QGIS_PLUGINPATH,QGIS_SERVER_PLUGIN_ProjectInfo'
    networks:
      - qgis-server-net
    ports:
      - "8080:80"  # Note: Sourcepole image uses port 80 inside the container
    volumes:
      # Mount projects directory to /data (where the Sourcepole image expects it)
      - ./projects:/data:ro
      # Mount custom plugins
      - ./plugins:/usr/share/qgis/python/plugins:ro
    restart: unless-stopped

networks:
  qgis-server-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: