version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - qgis-server-net
    depends_on:
      - qgis-server


  qgis-server:
    image: "qgis/qgis-server:ltr"
    environment:
      QGIS_PLUGINPATH: "/io/plugins"
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: "4"
      #QGIS_SERVER_WMS_MAX_HEIGHT: "5000"
      #QGIS_SERVER_WMS_MAX_WIDTH: "5000"
      #QGIS_SERVER_LOG_LEVEL: "0"
      QGIS_SERVER_LOG_STDERR: "true"
      # Enable our plugin
      QGIS_SERVER_PLUGIN_ProjectInfo: "1"
    networks:
      - qgis-server-net
    volumes:
      - ./projects:/io/data:ro
      - ./plugins:/io/plugins
      - ./nginx-conf/api-endpoints.conf:/etc/nginx/conf.d/api-endpoints.conf:ro

    restart: unless-stopped
    ports:
      - "8010:80"


networks:
  qgis-server-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: